### ISSUE TITLE
no litetable.cls in ctan?

### ISSUE THREAD

**Issue by kberry** [myhsia/litetable#2]
I went to update litetable in TeX Live with the new release of litetable, but noticed there is no litetable.cls on CTAN now. Is that intentional? Seemed problematic ...

**Comment by myhsia** [comment]
The CTAN team has already installed the new release, maybe the mirrors in your region have not synced to CTAN. So, you can switch to another mirror source, or wait until the mirrors in your region are up to date.

(P.S.: In my region, I also could not update it now, it may be available later today, or tomorrow)

[Image.png]

Best wishes,
Mingyu XIA
________________________________
From: kberry ***@***.***>
Sent: Tuesday, October 1, 2024 4:13:07 AM
To: xiamyphys/litetable ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xiamyphys/litetable] no litetable.cls in ctan? (Issue #2)


I went to update litetable in TeX Live with the new release of litetable, but noticed there is no litetable.cls on CTAN now. Is that intentional? Seemed problematic ...
